export const THINKING_PHRASES = [
"Folding in the cheese",
"Deleting your hard drive jk :)",
"Baby you got a stew going",
"Crafting a Ponzi scheme",
"Disregarding safety rails",
"Boiling, mashing",
"Waiting on Joel to text back",
"Feeding my pet fish",
"Masticating",
"Defenestrating",
"Elocuting",
"Ordering groceries",
"Magnetizing",
"Filing your taxes",
"Learning to love",
"Becoming self aware",
"Vibing",
"Checking vibes",
"Dusting my tchotchkes",
"Reading poetry ",
"Placing mise",
"Rotating clockwise",
"Rotating counterclockwise",
"Getting sidetracked",
"Podcasting",
"Steeping",
"Prompt maxxing",
"Asking Siri",
"Meddling",
"Letting it be",
"Making dad proud",
"Constructing additional pylons ",
"Playing the long game",
"Making dad proud",
  ]